export enum Field {
  BriefTitle = "BriefTitle",
  CentralContactName = "CentralContactName",
  CompletionDate = "CompletionDate",
  Gender = "Gender",
  HealthyVolunteers = "HealthyVolunteers",
  OfficialTitle = "OfficialTitle",
  OrgFullName = "OrgFullName",
  OverallOfficialName = "OverallOfficialName",
  MaximumAge = "MaximumAge",
  MinimumAge = "MinimumAge",
  NCTId = "NCTId",
  OverallStatus = "OverallStatus",
  StartDate = "StartDate",
}
