export enum Field {
  BriefTitle = "BriefTitle",
  CentralContactName = "CentralContactName",
  CompletionDate = "CompletionDate",
  Gender = "Gender",
  HealthyVolunteers = "HealthyVolunteers",
  OfficialTitle = "OfficialTitle",
  OrgFullName = "OrgFullName",
  OverallOfficialName = "OverallOfficialName",
  MaximumAge = "MaximumAge",
  MinimumAge = "MinimumAge",
  NCTId = "NCTId",
  OverallStatus = "OverallStatus",
  StartDate = "StartDate",
  Acronym = "Acronym",
  Condition = "Condition",
  LocationState = "LocationState",
  LocationCity = "LocationCity",
  LocationCountry = "LocationCountry",
  CollaboratorName = "CollaboratorName",
  LeadSponsorName = "LeadSponsorName",
  LocationContactName = "LocationContactName",
  LocationFacility = "LocationFacility",
  InterventionName = "InterventionName",
}
