export interface Owners {
    [key: string]: any;
    ASSOCIATE_ID_OWNER:                     string;
    TYPE_OWNER:                             string;
    ROLE_CODE_OWNER:                        string;
    ROLE_TEXT_OWNER:                        string;
    ASSOCIATION_DATE_OWNER:                 string;
    FIRST_NAME_OWNER:                       string;
    MIDDLE_NAME_OWNER:                      string;
    LAST_NAME_OWNER:                        string;
    TITLE_OWNER:                            string;
    ORGANIZATION_NAME_OWNER:                string;
    DOING_BUSINESS_AS_NAME_OWNER:           string;
    ADDRESS_LINE_1_OWNER:                   string;
    ADDRESS_LINE_2_OWNER:                   string;
    CITY_OWNER:                             string;
    STATE_OWNER:                            string;
    ZIP_CODE_OWNER:                         string;
    PERCENTAGE_OWNERSHIP:                   string;
    CREATED_FOR_ACQUISITION_OWNER:          string;
    CORPORATION_OWNER:                      string;
    LLC_OWNER:                              string;
    MEDICAL_PROVIDER_SUPPLIER_OWNER:        string;
    MANAGEMENT_SERVICES_COMPANY_OWNER:      string;
    MEDICAL_STAFFING_COMPANY_OWNER:         string;
    HOLDING_COMPANY_OWNER:                  string;
    INVESTMENT_FIRM_OWNER:                  string;
    FINANCIAL_INSTITUTION_OWNER:            string;
    CONSULTING_FIRM_OWNER:                  string;
    FOR_PROFIT_OWNER:                       string;
    NON_PROFIT_OWNER:                       string;
    OTHER_TYPE_OWNER:                       string;
    OTHER_TYPE_TEXT_OWNER:                  string;
}