// TODO - remove this file

export default {
  payments: [
    {
      id: "478941713",
      doctorId: "234",
      doctorName: "John Doe",
      manufacturerName: "Allergan Inc.",
      manufacturerId: "100000000278",
      amount: 500.00,
      date: "2017-05-31T00:00:00.000Z",
      year: "2017",
      paymentType: "In-kind items and services",
      paymentNature: "Food and Beverage",
      productType: "Drug",
      productCategory: "Neuroscience",
      productName: "Drug Name",
      contextualInfo: null,
    },
    {
      id: "478941713",
      doctorId: "567",
      doctorName: "Jane Doe",
      manufacturerName: "Allergan Inc.",
      manufacturerId: "100000000278",
      amount: 250.00,
      date: "2017-05-31T00:00:00.000Z",
      year: "2017",
      paymentType: "In-kind items and services",
      paymentNature: "Food and Beverage",
      productType: "Drug",
      productCategory: "Neuroscience",
      productName: "Drug Name",
      contextualInfo: null,
    },
    {
      id: "478941713",
      doctorId: "234",
      doctorName: "John Doe",
      manufacturerName: "Allergan Inc.",
      manufacturerId: "100000000278",
      amount: 500,
      date: "2017-05-31T00:00:00.000Z",
      year: "2017",
      paymentType: "In-kind items and services",
      paymentNature: "Food and Beverage",
      productType: "Drug",
      productCategory: "Neuroscience",
      productName: "Drug Name",
      contextualInfo: null,
    },
  ],
  rank: 775545,
  totalAmount: 153.73,
  topProducts: [
    {
      productName: "MD cobas Instruments and Reagents",
      amount: 20.28,
      type: "Device",
      count: 1,
    },
    { productName: "XARELTO", amount: 93.52, type: "Drug", count: 3 },
    { productName: "ELIQUIS", amount: 11.94, type: "Drug", count: 1 },
    { productName: "DALVANCE", amount: 27.99, type: "Drug", count: 2 },
  ],
  topManufacturers: [
    {
      manufacturerName: "Roche Diagnostics Corporation",
      amount: 20.28,
      count: 1,
    },
    {
      manufacturerName: "Janssen Pharmaceuticals, Inc",
      amount: 93.52,
      count: 3,
    },
    {
      manufacturerName: "Bristol-Myers Squibb Company",
      amount: 11.94,
      count: 1,
    },
    { manufacturerName: "Allergan Inc.", amount: 27.99, count: 2 },
  ],
};
