export enum Tab {
  Transactions = "Transactions",
  Manufacturers = "Manufacturers",
  Genetics = "Genetics",
  Diseases = "Diseases",
  Doctors = "Doctors",
  Products = "Products",
  Drugs = "Drugs",
  Food = "Food",
  ClinicalTrials = "ClinicalTrials",
  Plans = "Plans",
  PaymentsToDoctors = "PaymentsToDoctors",
  Hospitals = "Hospitals",
  HospitalOwners = "HospitalOwners",
  OpioidTreatmentProviders = "OpioidTreatmentProviders",
}
